burger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
    path('manager/', include("manager.urls", namespace="manager"))
    
]



if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

manager/urls.py
from django.urls import path
from manager import views

app_name = "manager"

urlpatterns = [
    
   path("", views.index, name="index"),
   path("login/", views.login, name="login"),
   path("logout/", views.logout, name="logout"),
   path("store_categories/", views.store_categories, name="store_categories"),
   path("store_category/add", views.store_category_add, name="store_category_add"),
   path("store_category_edit/<int:id>/", views.store_category_edit, name="store_category_edit"),
   path("store_category_delete/<int:id>/", views.store_category_delete, name="store_category_delete"),
   path("store/", views.store, name="store"),
   path("store_add", views.store_add, name="store_add"),
   path("store_edit/<int:id>/", views.store_edit, name="store_edit"),
   path("store_delete/<int:id>/", views.store_delete, name="store_delete"),
   path("food/", views.food, name="food"),
   path('food_add/', views.food_add, name='food_add'),
   path("food_edit/<int:id>/", views.food_edit, name="food_edit"),
   path("food_delete/<int:id>/", views.food_delete, name="food_delete"),
   path("food_categories/", views.food_categories, name="food_categories"),
   path("food_category_add/", views.food_category_add, name="food_category_add"),
   path("food_category_edit/<int:id>/", views.food_category_edit, name="food_category_edit"),
   path("food_category_delete/<int:id>/", views.food_category_delete, name="food_category_delete"),
   path("order/", views.order, name="order"),
   path("users/", views.users, name="users"),
   path("users_delete/<int:id>/", views.users_delete, name="users_delete"),
   path("users_edit/<int:id>/", views.users_edit, name="users_edit"),
   path("users_add/", views.users_add, name="users_add"),
   # path("customer/", views.customer, name="customer"),
   path("offers/", views.offers, name="offers"),
   path("offers_add", views.offers_add, name="offers_add"),
   path("offers_edit/<int:id>/", views.offers_edit, name="offers_edit"),
   path("offers_delete/<int:id>/", views.offers_delete, name="offers_delete"),
   path("slider/", views.slider, name="slider"),
   path("slider_add", views.slider_add, name="slider_add"),
   path("slider_edit/<int:id>/", views.slider_edit, name="slider_edit"),
   path("slider_delete/<int:id>/", views.slider_delete, name="slider_delete"),  
   
]

web/urls.py
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
   path("", views.index, name="index"),
   path("login/", views.login, name="login"),
   path("register/", views.register, name="register"),
   path("logout/", views.logout, name="logout"),
   path("restaurants/<int:id>/", views.restaurants, name="restaurants"),
   path("single_rest/<int:id>/", views.single_rest, name="single_rest"),
   path("cart/", views.cart, name="cart"),
   path("add_cart/<int:id>/", views.add_cart, name="add_cart"),
   path("cart_plus/<int:id>/", views.cart_plus, name="cart_plus"),
   path("cart_minus/<int:id>/", views.cart_minus, name="cart_minus"),   
   path("add_address/", views.add_address, name="add_address"),
   path("address/", views.address, name="address"),
   path("offer/", views.offer, name="offer"),
   path("checkout/", views.checkout, name="checkout"),   
   path("order/", views.order, name="order"), 
   path('validate_email/', views.validate_email, name='validate_email'),
   path("account/", views.account, name="account"),
   path("single_order/<int:id>/", views.single_order, name="single_order"), 
   path("creat_order/", views.creat_order, name="creat_order"),     
   path('address/delete/<int:id>/', views.address_delete,name="address_delete"),
   path('address/edit/<int:id>/', views.address_edit,name="address_edit"),
   path('address/select/<int:id>/', views.address_select,name="address_select"),
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
]

manager/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from users.manager import UserManager


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, max_length=256, error_messages={'unique': 'email aleardy exists'})
    is_customer = models.BooleanField(default=False)
    is_store = models.BooleanField(default=False)
    is_agent = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    
    objects = UserManager()
    
    class meta:
        db_table = "users_user"
        verbose_name = "User"
        verbose_name_plural = "Users"
        ordering = ['-id']
        
    def __str__(self):
        return self.email

manager/views.py
from django.shortcuts import render, reverse, redirect
from restaurant.models import *
from customer.models import *
from django.http import HttpResponseRedirect, HttpResponse
from manager.forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from main.functions import generate_form_errors
from main.decorators import allow_manager

@allow_manager
@login_required(login_url='/login/')
def index(request):
    
    return render(request,'manager/index.html')

def login(request):
    if request.method == "POST":
        form = ManagerLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)

            if user is not None:
                if user.is_manager: 
                    auth_login  (request,user)
                    return redirect('manager:index') 
                else:
                    messages.error(request, "Unauthorized access.")
                    return HttpResponse("unauthorized", status=401)
            else:
                messages.error(request, "Invalid email or password")
        else:
            messages.error(request, "Form is invalid.")
    else:
        form = ManagerLoginForm()

    return render(request, 'manager/login.html', {'form': form})

def logout(request):
    return redirect('manager:login')
@allow_manager
@login_required(login_url='/login/')
def store_categories(request):
    instances = StoreCategory.objects.all()
    
    context = {
        'instances': instances,
    }
    
    
    return render(request,'manager/store_categories.html', context=context)
@allow_manager
@login_required(login_url='/login/')

def store_category_delete(request,id):
    instance = StoreCategory.objects.get(id=id)
     
    instance.delete()
    
    return HttpResponseRedirect(reverse('manager:store_categories'))
@login_required(login_url='/login/')
def store_category_add(request,):
    if request.method == 'POST':   
        form = StoreCategoryform(request.POST, request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:store_categories'))
            
        else:
            message = generate_form_errors(form)
            form = StoreCategoryform()

            context = {
            "error": True,
            "message": message,
            "form": form,
            }
    
        return render(request,'manager/store_categories_add.html', context=context)



    else:
        form = StoreCategoryform()
        
        context = {
            "form": form,
        }
        
    return render(request,'manager/store_categories_add.html', context=context)
@login_required(login_url='/login/')
def store_category_edit(request, id):
    instance = StoreCategory.objects.get(id=id)
    if request.method == 'POST':   
        form = StoreCategoryform(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:store_categories'))
            
        else:
            message = generate_form_errors(form)
            form = StoreCategoryform()

            context = {
            "error": True,
            "message": message,
            "form": form,
            "instance": instance,
            }
    
        return render(request,'manager/store_categories_add.html', context=context)



    else:
        form = StoreCategoryform(instance=instance)
        
        context = {
            "form": form,
            "instance": instance,
        }
        
    return render(request,'manager/store_categories_add.html', context=context)
        
    
@allow_manager
@login_required(login_url='/login/')

def store(request):
    instances = Store.objects.all()
    
    context = {
        'instances': instances,
    }
    
    
    return render(request,'manager/store.html', context=context)
@allow_manager
@login_required(login_url='/login/')

def store_delete(request,id):
    instance = Store.objects.get(id=id)
    
    instance.delete()
    
    return HttpResponseRedirect(reverse('manager:store'))
@allow_manager
@login_required(login_url='/login/')
def store_add(request,):
    if request.method == 'POST':   
        form = Storeform(request.POST, request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:store'))
            
        else:
            message = generate_form_errors(form)
            form = Storeform()

            context = {
            "error": True,
            "message": message,
            "form": form,  
            }
    
        return render(request,'manager/store_add.html', context=context)



    else:
        form = Storeform()
        
        context = {
            "form": form,
        }
        
    return render(request,'manager/store_add.html', context=context)

@allow_manager
@login_required(login_url='/login/')
def store_edit(request, id):
    instance = Store.objects.get(id=id)
    if request.method == 'POST':   
        form = Storeform(request.POST, request.FILES,instance=instance)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:store'))
            
        else:
            message = generate_form_errors(form)
            form = Storeform()

            context = {
            "error": True,
            "message": message,
            "form": form,
            "instance": instance,
            
            }
    
        return render(request,'manager/store_add.html', context=context)



    else:
        form = Storeform(instance=instance)
        
        context = {
            "form": form,
            "instance": instance,
            
        }
        
    return render(request,'manager/store_add.html', context=context)






@allow_manager
@login_required(login_url='/login/')

def slider(request):
    instances = Slider.objects.all()
    
    context = {
        'instances': instances,
    }
    
    
    return render(request,'manager/slider.html', context=context)
@allow_manager
@login_required(login_url='/login/')

def slider_delete(request,id):
    instance = Slider.objects.get(id=id)
    
    instance.delete()
    
    return HttpResponseRedirect(reverse('manager:slider'))
@allow_manager
@login_required(login_url='/login/')
def slider_add(request,):
    if request.method == 'POST':   
        form = SliderForm(request.POST, request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:slider'))
            
        else:
            message = generate_form_errors(form)
            form = SliderForm()

            context = {
            "error": True,
            "message": message,
            "form": form,
            }
    
        return render(request,'manager/slider_add.html', context=context)



    else:
        form = SliderForm()
        
        context = {
            "form": form,
        }
        
    return render(request,'manager/slider_add.html', context=context)
@allow_manager
@login_required(login_url='/login/')
def slider_edit(request,id):
    instance = Slider.objects.get(id=id)
    if request.method == 'POST':   
        form = SliderForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:slider'))
            
        else:
            message = generate_form_errors(form)
            form = SliderForm()

            context = {
            "error": True,
            "message": message,
            "form": form,
            "instance": instance
            }
    
        return render(request,'manager/slider_add.html', context=context)



    else:
        form = SliderForm(instance=instance)
        
        context = {
            "form": form,
            "instance": instance
        }
        
    return render(request,'manager/slider_add.html', context=context)
@allow_manager
@login_required(login_url='/login/')

def food_categories(request):
    instances = FoodCategory.objects.all()
    
    context = {
        'instances': instances,
    }
    
    
    return render(request,'manager/food_categories.html', context=context)
@allow_manager
@login_required(login_url='/login/')

def food_category_delete(request,id):
    instance = FoodCategory.objects.get(id=id)
    
    instance.delete()
    
    return HttpResponseRedirect(reverse('manager:food_categories'))

@allow_manager
@login_required(login_url='/login/')
def food_category_add(request,):
    if request.method == 'POST':   
        form = FoodCategoryform(request.POST, request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:food_categories'))
            
        else:
            message = generate_form_errors(form)
            form = FoodCategoryform()

            context = {
            "error": True,
            "message": message,
            "form": form,
            }
    
        return render(request,'manager/food_category_add.html', context=context)



    else:
        form = FoodCategoryform()
        
        context = {
            "form": form,
        }
        

users/views.py
from django.shortcuts import render

# Create your views here.

templates/manager/food.html
{% extends 'base/manager-base.html' %}

{% load static %}

{% block container %}




{% include 'includes/manager-nav.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Food List</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>NAME</th>
                                                <th>IMAGE</th>
                                                <th>FOODCATEGORY</th>
                                                <th>STORE</th>
                                                <th>IS_VEG</th>
                                                <th>PRICE</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                                <th>ADD</th>
                                            </tr>
                                        </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{instance.id}}</td>
                                            <td>{{instance.name}}</td>
                                            <td><img src="{{instance.image.url}}" alt="image" style="width: 70px;"></td>
                                            <td>{{instance.foodcategory}}</td>
                                            <td>{{instance.store}}</td>
                                            <td>{{instance.is_veg}}</td>
                                             <td>{{instance.price}}</td>
                                            <td><a href="{% url 'manager:food_edit' id=instance.id %}"><button type="button" class="btn mb-1 btn-primary">Edit</button></a></td>
                                            <td><a href="{% url 'manager:food_delete' id=instance.id %}"><button type="button" class="btn mb-1 btn-danger" >Delete</button></a></td>
                                            <td><a href="{% url 'manager:food_add'  %}"><button type="button" class="btn mb-1 btn-primary">Add</button></a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

{% endblock %}

templates/manager/food_categories.html
{% extends 'base/manager-base.html' %}

{% load static %}

{% block container %}




{% include 'includes/manager-nav.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Store Category List</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>NAME</th>
                                                <th>STORE</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                                <th>ADD</th>
                                            </tr>
                                        </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{instance.id}}</td>
                                            <td>{{instance.name}}</td>
                                            <td>{{instance.store}}</td>
                                            <td><a href="{% url 'manager:food_category_edit' id=instance.id %}"><button type="button" class="btn mb-1 btn-primary">Edit</button></a></td>
                                            <td><a href="{% url 'manager:food_category_delete' id=instance.id %}"><button type="button" class="btn mb-1 btn-danger" >Delete</button></a></td>
                                            <td><a href="{% url 'manager:food_category_add'  %}"><button type="button" class="btn mb-1 btn-primary">Add</button></a></td>

                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

{% endblock %}

templates/manager/offers.html
{% extends 'base/manager-base.html' %}

{% load static %}

{% block container %}




{% include 'includes/manager-nav.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Offer List</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>CODE</th>
                                                <th>DISCOUNT</th>
                                                <th>DESCEIBTION</th>
                                                <th>PERCENTAGE</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                                <th>ADD</th>
                                            </tr>
                                        </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{instance.id}}</td>
                                            <td>{{instance.code}}</td>
                                            <td>{{instance.discount}}</td>
                                            <td>{{instance.short_description}}</td>
                                            <td>{{instance.is_percentage}}</td>
                                            <td><a href="{% url 'manager:offers_edit' id=instance.id %}"><button type="button" class="btn mb-1 btn-primary">Edit</button></a></td>
                                            <td><a href="{% url 'manager:offers_delete' id=instance.id %}"><button type="button" class="btn mb-1 btn-danger" >Delete</button></a></td>
                                            <td><a href="{% url 'manager:offers_add'  %}"><button type="button" class="btn mb-1 btn-primary">Add</button></a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

{% endblock %}

templates/manager/slider.html
{% extends 'base/manager-base.html' %}

{% load static %}

{% block container %}




{% include 'includes/manager-nav.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Slider List</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>NAME</th>
                                                <th>IMAGE</th>
                                                <th>STORE</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                                <th>ADD</th>
                                            </tr>
                                        </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{instance.id}}</td>
                                            <td>{{instance.name}}</td>
                                            <td><img src="{{instance.image.url}}" alt="image" style="width: 70px;"></td>
                                            <td>{{instance.store}}</td>
                                            <td><a href="{% url 'manager:slider_edit' id=instance.id %}"><button type="button" class="btn mb-1 btn-primary">Edit</button></a></td>
                                            <td><a href="{% url 'manager:slider_delete' id=instance.id %}"><button type="button" class="btn mb-1 btn-danger" >Delete</button></a></td>
                                            <td><a href="{% url 'manager:slider_add'  %}"><button type="button" class="btn mb-1 btn-primary">Add</button></a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

{% endblock %}