burger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
    path('manager/', include("manager.urls", namespace="manager"))
    
]



if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

web/urls.py
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
   path("", views.index, name="index"),
   path("login/", views.login, name="login"),
   path("register/", views.register, name="register"),
   path("logout/", views.logout, name="logout"),
   path("restaurants/<int:id>/", views.restaurants, name="restaurants"),
   path("single_rest/<int:id>/", views.single_rest, name="single_rest"),
   path("cart/", views.cart, name="cart"),
   path("add_cart/<int:id>/", views.add_cart, name="add_cart"),
   path("cart_plus/<int:id>/", views.cart_plus, name="cart_plus"),
   path("cart_minus/<int:id>/", views.cart_minus, name="cart_minus"),   
   path("add_address/", views.add_address, name="add_address"),
   path("address/", views.address, name="address"),
   path("offer/", views.offer, name="offer"),
   path("checkout/", views.checkout, name="checkout"),   
   path("order/", views.order, name="order"), 
   path('validate_email/', views.validate_email, name='validate_email'),
   path("account/", views.account, name="account"),
   path("single_order/<int:id>/", views.single_order, name="single_order"), 
   path("creat_order/", views.creat_order, name="creat_order"),     
   path('address/delete/<int:id>/', views.address_delete,name="address_delete"),
   path('address/edit/<int:id>/', views.address_edit,name="address_edit"),
   path('address/select/<int:id>/', views.address_select,name="address_select"),
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
]

restaurant/models.py
from django.db import models


class StoreCategory(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='categories')
    
    
    
    class meta:
           db_table = "restaurant_store_category"
           verbose_name = "store_category"
           verbose_name_plural = "store_categories"
           ordering = ['-id']
    
    
    def __str__(self):
          return self.name



class Store(models.Model):
    name =  models.CharField(max_length=100)
    category = models.ForeignKey(StoreCategory, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store')
    taglin = models.CharField(max_length=255)
    rating = models.FloatField()
    time = models.IntegerField()
    
    
    class meta:
        db_table = "restaurant_store"
        verbose_name = "store"
        verbose_name_plural = "stores"
        ordering = ['-id']
    
    
    def __str__(self):
        return self.name
    
    
class Slider(models.Model):
    name =  models.CharField(max_length=255)
    image = models.ImageField(upload_to='slider')
    store= models.ForeignKey(Store, on_delete=models.CASCADE)
    
    
    class meta:
        db_table = "restaurant_slider"
        verbose_name = "slider"
        verbose_name_plural = "sliders"
        ordering = ['-id']
    
    
    def __str__(self):
        return self.name
    
class FoodCategory(models.Model):
    name = models.CharField(max_length=255)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    
    
    
        
    class meta:
        db_table = "foodcategory"
        verbose_name = "foodcategory"
        verbose_name_plural = "foodcategories"
        ordering = ['-id']
    
    
    def __str__(self):
        return self.name
    
    
class Food(models.Model):
    name = models.CharField(max_length=255)
    price = models.FloatField()
    is_veg = models.BooleanField(default=False)
    image = models.ImageField(upload_to="Food")
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    foodcategory = models.ForeignKey(FoodCategory, on_delete=models.CASCADE)
    
    
    
    
    
    class meta:
        db_table = "food"
        verbose_name = "food"
        verbose_name_plural = "foods"
        ordering = ['-id']
    
    
    
    
    def __str__(self):
        return self.name
    

restaurant/views.py
from django.shortcuts import render

# Create your views here.

templates/web/account.html
{% extends 'base/web-base.html' %}
{% block container %}
{% load static %}

    <header class="h-[80px] flex items-center px-[15px]">
        <a href="{% url 'web:index'%} " class=""><img src="{% static '/web/images/arrow.png' %}" alt="arrow" class="h-[40px]" ></a>
        <h1 class="text-center relative left-[45%]  text-[22px] font-[600]">Account</h1>
    </header>

    <section class="wrapper py-16 flex items-center ">
      <div class="w-[30%]">
        <div class="  flex items-center border px-[90px] py-[55px] rounded-2xl ">
            <div class="mr-[20px]">
                <img src="{% static '/web/images/man.png' %}" alt="man" class="w-[100px]">
            </div>
            <div class="mr-[20px] ">
                <h1 class=" text-[20px] font-semibold mb-3  ">Muhammed Migdad</h1>
                <span class=" text-[20px] font-semibold mb-2">+91 7902467062</span>
                <p class=" text-[20px] font-semibold mt-2 ">migdad@tegrand.in</p>
            </div>
        </div>
        <ul class=" flex items-center border px-5 py-2 rounded-2xl  bg-[#23b56e] mt-[30px]">
            <a href="{% url 'web:address'%}">
                <img class="mr-[20px] w-[30px]" src="{% static '/web/images/address.png' %}" alt="">
            </a>
                <li class="text-[20px] font-semibold text-[#fff]">Manage Address</li>
        </ul>
        <ul class=" flex items-center border px-5 py-2 rounded-2xl  bg-[#23b56e] mt-[30px]">
            <a href="{% url 'web:order'%}">
                <img class="mr-[20px] w-[30px]" src="{% static '/web/images/cart.png' %}" alt="">
            </a>
                <li class="text-[20px] font-semibold text-[#fff]">Orders</li>
        </ul>
        <ul class=" flex items-center border px-5 py-2 rounded-2xl  bg-[#23b56e] mt-[30px]">
            <a href="{% url 'web:logout'%}">
                <img class="mr-[20px] w-[30px]" src="{% static '/web/images/logout.png' %}" alt="">
            </a>
                <li class="text-[20px] font-semibold text-[#fff]">Logout</li>
        </ul>
      </div>
      <div class="ml-[100px] w-[68%]">
        <h1 class="text-[23px] text-center font-semibold">Recent Orders</h1>
        <section class="max-w-4xl mx-auto mt-10  ">
            {% if order %}
                <div class="grid gap-8">
                    {% for order in order %}
                        <div class="block border border-gray-200 rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300 ease-in-out px-[50px] py-[20px] bg-white">
                            <div class="flex justify-between items-center">
                                <h2 class="text-2xl font-semibold text-gray-800">Order #{{ order.id }}</h2>
                                <span class="px-3 py-1 text-sm font-medium rounded-full bg-purple-100 text-purple-800">
                                    Placed on: {{ order.created_at|date:"F j, Y" }}
                                </span>
                            </div>
                            
                            <div class="mt-4">
                                <h3 class="text-lg font-semibold text-gray-800">Items:</h3>
                                <ul class="mt-2 space-y-1">
                                    {% for item in order.cartbill.all %}
                                        <li class="flex justify-between items-center">
                                            <span class="text-gray-700">{{ item.product.name }} (x{{ item.quantity }})</span>
                                            <span class="text-green-600 font-semibold">₹{{ item.price }}</span>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
    
                            <div class="mt-4 flex justify-between items-center">
                                <p class="text-xl font-bold text-gray-900 mr-[20px]">Total: ₹{{ order.totel_amount }}</p>
                                <a href="{% url 'web:single_order' id=order.id %}">
                                    <span class="px-4 py-2 text-sm font-medium rounded-lg bg-green-500 text-white">TRACK ORDER</span>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="text-center mt-20">
                    <p class="text-2xl font-semibold text-gray-700">You have no orders yet.</p>
                    <a href="{% url 'web:index' %}" class="mt-6 inline-block bg-gradient-to-r from-purple-500 via-pink-500 to-red-500 text-white font-semibold py-3 px-6 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 ease-in-out">
                        Shop Now
                    </a>
                </div>
            {% endif %}
        </section>
    
      </div>
     
    </section>

{%endblock%}
    

templates/web/address.html
{% extends 'base/web-base.html' %}
{% block container %}
{% load static %}



<header class="h-[80px] flex items-center px-[15px]">
    <a class="h-[100%]" href="{% url 'web:cart'%}"><img src="{% static '/web/images/arrow.png' %}" alt="arrow" class="h-[40%] mt-[20px]"></a>
    <h1 class="text-center relative left-[43%] text-[22px] font-[600]">Address</h1>
</header>

<section class="px-[15px]">
    <div class="max-w-[620px] py-[10px] bg-red-600 text-white text-[18px] font-[600] text-center m-auto mt-[40px] hover:text-black rounded-[5px] items-center">
       <a href="{% url 'web:add_address'%}">ADD NEW ADDRESS</a>
    </div>
    {% for address in current_address %}
    <div class="flex justify-between bg-[#c6c6bb54] h-[150px] max-w-[620px] m-auto px-[20px] mt-[20px] items-center rounded-[5px]">
        <div class="bg-white rounded-[50%] w-[50px] sm:w-[100px] h-[50px] sm:h-[100px] flex justify-center items-center">
            {% if address.address_type == 'home' or not address.address_type %}
            <img src="{% static '/web/images/house.png' %}" alt="house" class="h-[80%] w-[80%]">
            {% elif address.address_type == 'work' %}
            <img src="{% static '/web/images/work.png' %}" alt="house" class="h-[80%] w-[80%]">
            {% endif %}
        </div>
        <ul>
            <li class="text-[20px] font-[500]">{{ address.address_type|upper }}</li>
            <li class="text-[10px] sm:text-[14px] font-[600]">{{address.address}}, {{address.appartment}}, {{address.landmark}}, {{address.phone_number}}</li>
        </ul>
        <div class="flex h-[100%] items-center">
            <a href="{% url 'web:address_select' address.id %}">
            <img src="{% static '/web/images/checkmark.png' %}" alt="tick" class="h-[15px] mr-[10px]">
            </a>
            <a href="{% url 'web:address_edit' id=address.id %}">
               <img src="{% static '/web/images/edit.png' %}" alt="edit" class="h-[15px] mr-[10px]">
            </a>
            <a href="{% url 'web:address_delete' id=address.id %}">
               <img src="{% static '/web/images/delet.png' %}" alt="delete" class="h-[15px]">
               </a>
        </div>
    </div>
    {% endfor %}
</section>
{% endblock %}

templates/web/cart.html
{% extends 'base/web-base.html' %}
{% block container %}
{% load static %}


    {% if store %}
    <header class="h-[80px] flex items-center px-[15px]">
        <a class="h-[100%]" href="{% url 'web:index'%}"><img src="{% static '/web/images/arrow.png' %}" alt="arrow" class="h-[40px] mt-[20px]"></a>
        <h1 class="text-center relative left-[45%]  text-[22px] font-[600]">Cart</h1>
    </header>

    <section class="px-[15px] text-[#000] ">
        <div class="shadow-md offset-y-2 opacity-90 flex max-w-[620px] h-[150px] sm:h-[200px] p-[20px] border-[1px] border-[#d4d2d2] rounded-[5px] m-auto mt-[30px] mb-[50px]">
            <img src="{{store.image.url}}" alt="rest" class="h-[100%] rounded-[5px] mr-[15px]">
            <div class="mt-[-8px]">
                <h1 class="text-[16px] sm:text-[22px] font-[600] mb-[5px]">{{store.name}}</h1>
                <h3 class="mb-[5px]">{{store.taglin}}</h3>
                <ul class="flex mb-[5px]">
                    <li class="flex mr-[15px] items-center">
                        <img src="{% static '/web/images/star.png' %}" alt="star" class="h-[20px] mr-[10px]">
                        <p class="text-[15px] sm:text-[18px] font-[600]">{{store.rating}}</p>
                    </li>
                    <li class="flex mr-[15px] items-center">
                        <img src="{% static '/web/images/clock.png' %}" alt="clock" class="h-[20px] mr-[10px]">
                        <p class="text-[15px] sm:text-[18px] font-[600]">{{store.time}}mins</p>     
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <section class="px-[15px]">
        <ul class="px-[20px] py-[10px] max-w-[620px] m-auto shadow-md offset-y-2 opacity-90 border-[1px] border-[#d4d2d2] rounded-[5px]">
            <li class="text-[22px] w-[100%] border-b-[1px] border-[#d4d2d2]">
                ITEMS IN CART
            </li>
            {% for item in cart_items %}
            <li class=" w-[100%] border-b-[1px] border-[#d4d2d2] items-center py-[10px]">
                    <div class="flex justify-between">
                        <div>
                            <h3>
                                {{item.product.name}}
                            </h3>
                            <span class="font-[500]">{{item.product.price}}</span>
                        </div>
                        <div class="w-[60px] flex justify-between">
                            <a href="{% url 'web:cart_minus' id=item.product.id %}" class="bg-[#2AC489] w-[33%] rounded-l-[5px] text-white text-center h-[50%]">-</a>
                            <span>{{item.quantity}}</span>
                            <a href="{% url 'web:cart_plus' id=item.product.id %}" class="bg-[#2AC489] w-[33%] rounded-r-[5px] text-white text-center h-[50%]">+</a>
                        </div> 
                    </div>
                </li>
                {% endfor %}
        </ul>


        <div class="px-[20px] py-[10px] max-w-[620px] m-auto shadow-md offset-y-2 opacity-90 border-[1px] border-[#d4d2d2] rounded-[5px] mt-[20px]">
            <div class=" w-[100%] border-b-[1px] border-[#d4d2d2] items-center py-[10px]">
                <form class="flex justify-between" method="post" action="">
                    {% csrf_token %}
                    <input type="text" placeholder="Coupon Code" name="code" class=" outline-none">
                    {% if error_message %}
                        <div class="alert alert-danger text-red-500 font-bold bg-red-50 p-2 rounded-md">
                            {{ error_message }}
                        </div>
                    {% endif %}

                    {% if success_message %}
                        <div class="alert alert-success text-green-500 font-bold bg-green-50 p-2 rounded-md">
                            {{ success_message }}
                        </div>
                    {% endif %}

                    <button type="submit" class="px-[18px] py-[6px] bg-[#2AC489] rounded-[5px] text-white font-[500]">
                    APPLY
                    </button>
                </form>
            </div>
            <div class="flex items-center mt-[10px]">
                <img src="{% static '/web/images/discount.png' %}" alt="dis" class="h-[20px] mr-[5px]">
                <a href="{% url 'web:offer'%}" class="text-red-600 font-[400]">View All Offers</a>
            </div>
        </div>
        <div class="px-[20px] py-[10px] max-w-[620px] m-auto shadow-md offset-y-2 opacity-90 border-[1px] border-[#d4d2d2] rounded-[5px] mt-[20px]">
            <h3 class="text-[20px] font-[500]">BILL DETAILS</h3>
            <ul>
                <li class="flex justify-between w-[100%] border-b-[1px] border-[#d4d2d2] items-center py-[10px]">
                    <p>Item Total</p>
                    <span>{{cartbill.item_total}}</span>
                </li>
                <li class="flex justify-between w-[100%] border-b-[1px] border-[#d4d2d2] items-center py-[10px]">
                    <p>Offer Applied</p>
                    <span>{{cartbill.offer_amount}}</span>
                </li>
                <li class="flex justify-between w-[100%] border-b-[1px] border-[#d4d2d2] items-center py-[10px]">
                    <p>delivery charges(4km)</p>
                    <span>{{cartbill.delivery_charge}}</span>
                </li>
                <li class="flex justify-between w-[100%] items-center py-[10px]">
                    <p class="text-[18px] font-[700]">To Pay</p>
                    <span class="text-[18px] font-[700]">{{cartbill.totel_amount}}</span>
                </li>
            </ul>
        </div>
        <div class="px-[20px] py-[10px] max-w-[620px] m-auto shadow-md offset-y-2 opacity-90 border-[1px] rounded-[5px] mt-[20px]">
            <div class="flex justify-between w-[100%] border-b-[1px] border-[#d4d2d2] items-center py-[10px]">
                <h3 class="text-[20px] font-[500]">
                    DELIVER TO
                </h3>
            </div>
            {% if address %}
            <div class="flex justify-between w-[100%] items-center py-[10px]">
                <p class="text-[13px] sm:text-[18px]">
                    {{address.address}}, {{address.appartment}}, {{address.landmark}}, {{address.phone_number}}
                </p>
                <a href="{% url 'web:address'%}">
                    <button class="px-[18px] py-[6px] bg-[#2AC489] rounded-[5px] text-white font-[500]">
                        CHANGE
                    </button>
                </a>
            </div>
                {% else %}
                <a href="{% url 'web:address'%}">
                    <button class="px-[18px] py-[6px] bg-[#2AC489] rounded-[5px] text-white font-[500]">
                        ADD ADDRESS
                    </button>
                </a>
            {% endif %}
        </div>
        <a href="{% url 'web:checkout'%}">
            <div class="max-w-[620px] py-[10px] bg-red-600 text-white text-[18px] font-[600] text-center m-auto mt-[10px] rounded-[5px] items-center">
                CONTINUE
            </div>
        </a>
    </section>

    {% else %}

    <div class="bg-gray-100  h-screen">
        <div class="text-center">
            <svg class="w-[400px] h-[400px] mx-auto text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L6 6H4m3 7l1.4 5.4a2 2 0 002 1.6h7a2 2 0 002-1.6L17 13m-10 0h10m-6 5a1 1 0 101 1m-4 0a1 1 0 101 1"></path></svg>
            <h1 class="mt-4 text-2xl font-bold text-gray-700">Your Cart is Empty</h1>
            <p class="mt-2 text-gray-500">Looks like you haven't added anything to your cart yet.</p>
            <a href="/" class="mt-6 inline-block bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600">Continue Shopping</a>
        </div>
    </div>

{% endif %}
{%endblock%}

templates/web/offer.html
{% extends 'base/web-base.html' %}
    {% block container %}
    {% load static %}




    <header class="h-[80px] flex items-center px-[15px]">
        <a class="h-[100%]" href="{% url 'web:cart'%}"><img src="{% static '/web/images/arrow.png' %}" alt="arrow" class="h-[40px] mt-[20px]"></a>
        <h1 class="text-center relative left-[43%] text-[22px] font-[600]">Offers</h1>
    </header>

    <section class="px-[15px]">
        <div class="max-w-[620px] h-[140px] sm:h-[120px] shadow-md offset-y-2 opacity-90 m-auto px-[20px] mt-[40px]">
            <div class="flex justify-between h-[60%] items-center">
                <span class="text-[20px] font-[500]">
                    SBI40N
                </span>
                <a href="{% url 'web:cart'%}  " class="bg-[#29c46e] px-[16px] py-[8px] text-white font-[600] rounded-[5px]">
                    APPLY
                </a>
            </div>
            <p class="text-red-600 font-[500] h-[40%] items-center">Maximum discount upto ₹ 120 on orders above ₹ 200</p>
        </div>

        <div class="max-w-[620px] h-[140px] sm:h-[120px] shadow-md offset-y-2 opacity-90 m-auto px-[20px] mt-[20px]">
            <div class="flex justify-between h-[60%] items-center">
                <span class="text-[20px] font-[500]">
                    AXIS30
                </span>
                <a href="{% url 'web:cart'%}" class="bg-[#737574] px-[16px] py-[8px] text-white font-[600] rounded-[5px]">
                    APPLY
                </a>
            </div>
            <p class="font-[500] text-[#5d5f5e] h-[40%] items-center">Maximum discount upto ₹ 50 on orders above ₹ 500</p>
        </div>
    </section>
{% endblock %}

templates/web/single_rest.html
{% extends 'base/web-base.html' %}
{% block container %}
{% load static %}


    <header class="h-[80px] flex sm:flex-row justify-between px-[20px] items-center">
        <a href="{% url 'web:index'%}">
        <img src="{% static '/web/images/logo.png' %}" alt="logo" class="h-[60px] mb-2 sm:mb-0">
        </a>
        <div class="mt-2 hidden md:flex sm:mt-0">
            <ul class="h-[80px] flex items-center flex-wrap">
                <li class="mr-[15px] h-[20%] flex mb-2 sm:mb-0">
                    <img src="{% static '/web/images/home.png' %}" alt="home" class="h-[100%] mr-[5px] mt-[4px]">
                    <a href="{% url 'web:index'%}">Home</a>
                </li>
                <li class="mr-[15px] h-[20%] flex mb-2 sm:mb-0">
                    <img src="{% static '/web/images/search.png' %}" alt="search" class="h-[100%] mr-[5px] mt-[4px]">
                    <a href="#">Search</a>
                </li>
                <li class="mr-[15px] h-[20%] flex mb-2 sm:mb-0">
                    <img src="{% static '/web/images/bag.png' %}" alt="home" class="h-[100%] mr-[5px] mt-[4px]">
                    <a href="{% url 'web:cart'%}">Cart</a>
                </li>
                <li class="mr-[15px] h-[20%] flex mb-2 sm:mb-0">
                    <img src="{% static '/web/images/user.png' %}" alt="home" class="h-[100%] mr-[5px] mt-[4px]">
                    <a href="{% url 'web:account' %}">Account</a>
                </li>
            </ul>
        </div>
        <div class=" flex justify-end items-center">
            <a href="https://www.google.com/maps/place/Valanchery,+Kerala+676552/@10.8861438,76.0530061,15z/data=!3m1!4b1!4m6!3m5!1s0x3ba7b6328c091e7b:0x8b642b0d66d70d05!8m2!3d10.8877717!4d76.0732189!16s%">
                <img src="{% static 'web/images/map.png' %}" alt="map" class="w-[18px] mr-3">
            </a>
            <p class=" text-16px] font-semibold pb-1 border-b-2 border-yellow-400 mr-4">Valanchery, Malappuram</p>
        </div>
        <div class="md:hidden">
            <i id="mobile-menu" class='bx bx-menu-alt-right text-[25px] font-[500] mt-[4px]'></i>
        </div>
    </header>

    <div class="flex justify-end">
        <div id="mobile-drop" class="hidden px-[20px] w-[150px]">
            <ul class="">
                <li class="flex">
                    <img src="{% static '/web/images/home.png' %}" alt="home" class="h-[20px] mr-[10px]">
                    <a href="#" class="text-black text-[16px] font-[700]">Home</a>
                </li>
                <li class="flex">
                    <img src="{% static '/web/images/search.png' %}" alt="search" class="h-[20px] mr-[10px]">
                    <a href="#" class="text-black text-[16px] font-[700]">Search</a>
                </li>
                <li class="flex">
                    <img src="{% static '/web/images/bag.png' %}" alt="home" class="h-[20px] mr-[10px]">
                    <a href="#" class="text-black text-[16px] font-[700]">Cart</a>
                </li>
                <li class="flex">
                    <img src="{% static '/web/images/user.png' %}" alt="home" class="h-[20px] mr-[10px]">
                    <a href="#" class="text-black text-[16px] font-[700]">Account</a>
                </li>
            </ul>
        </div>
    </div>
    <section class="wrapper">
        <div class=" max-w-[620px] m-auto">
                <div class=" col-span-1 p-4 rounded-lg border-[#d4d2d2]  border">
                    <a href="#" class="flex justify-start">
                        <img src="{{store.image.url}}" alt="image" class="w-[35%] rounded-xl mr-4">
                        <div class="w-[65%]">
                            <h3 class=" text-[16px] font-semibold mb-1">{{store.name}}</h3>
                            <p class="text-[14px] mb-4">{{store.taglin}}</p>
                            <div class="flex justify-start items-center">
                                <span class=" flex justify-start items-center mr-4">
                                    <img src="{% static 'web/images/star.png' %}" alt="image" class="w-[16px] mr-2">
                                    {{store.rating}}
                                </span>
                                <span class="flex justify-start items-center">
                                    <img src="{% static 'web/images/clock.png' %}" alt="image" class="w-[16px] mr-2">
                                    {{store.time}} min
                                </span>
                            </div>
                        </div>
                    </a>
                </div>
        </div>
    </section>

    <section class="px-[15px] pt-10 text-[]">
        <div class="max-w-[620px] m-auto">
        {% for foodcategory in foodcategories %}
            <h2 class="mb-[40px] text-[28px] text-[#000] font-[600]">{{foodcategory.name}}</h2> 
        {% for food,quantity in prod_with_qty %}          
            <ul> 
                <li class="flex h-[150px] pb-[15px] border-[#d4d2d2]  border-b-[2px] w-[100%] mb-[30px]">
                    <div class="h-[100%] w-[100%]">
                        {% if food.is_veg %}
                        <img src="{% static 'web/images/veg.png' %}" alt="non" class="h-[20px]">
                        {% else %}
                        <img src="{% static 'web/images/non.png' %}" alt="non" class="h-[20px]">
                        {% endif %}
                        <h2 class="text-[20px] font-[600] text-[#000]">{{food.name}}</h2>
                        <span class="text-[20px] font-[600] block mb-2">{{food.price}}</span>
                        {% if quantity > 0 %}
                        <div class="w-[60px] flex justify-between">
                            <a href="{% url 'web:cart_minus' id=food.id %}" class="bg-[#2AC489] w-[33%] rounded-l-[5px] text-white text-center h-[100%]">-</a>
                            <span>{{quantity}}</span>
                            <a href="{% url 'web:cart_plus' id=food.id %}" class="bg-[#2AC489] w-[33%] rounded-r-[5px] text-white text-center h-[100%]">+</a>
                        </div> 
                        {% else %}
                        <a href="{% url 'web:add_cart' id=food.id %}" class="bg-[#45dd72] px-[12px] py-[6px] rounded-[5px] text-white font-[700] mt-[20px]">ADD</a>
                        {% endif %}
                    </div>
                    <img src="{{food.image.url}}" alt="rest" class="h-[100%] rounded-[5px]">
                </li>
            </ul> 
            
        {% endfor %} 
        {% endfor %}  
        </div>       
        <ul class="max-w-[640px] flex justify-between bg-[rgb(195,71,71)] m-auto h-[40px] items-center px-[15px] rounded-[5px] mb-[20px]">
            <li class="text-white font-[500]">
                1 Item | ₹ 180
            </li>
            <li class="flex items-center h-[100%]">
                <a href="{% url 'web:cart' %}" class="text-white font-[500]">View Cart</a>
                <img src="{% static '/web/images/cart.png' %}" alt="cart" class="h-[50%]">
            </li>
        </ul>
    </section>


    <script src="{% static 'web/js/index.js' %}"></script>
{% endblock %}